import React, { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    shopName:        'Choudhary Communications',
    welcome:         'Welcome to Choudhary Communications!',
    welcomeSubtitle: 'Your one-stop shop for mobiles, accessories & services',
    featuredItems:   'Featured Items',
    specialOffers:   'Special Offers',
    ourServices:     'Our Services',
    contactUs:       'Contact Us',
    whatsappUs:      'WhatsApp Us',
    callUs:          'Call Us',
    viewDetails:     'View Details',
    inStock:         'In Stock',
    outOfStock:      'Out of Stock',
    noOffers:        'No active offers right now',
    adminPanel:      'Admin Panel',
    dashboard:       'Dashboard',
    manageItems:     'Manage Items',
    manageOffers:    'Manage Offers',
    manageServices:  'Manage Services',
    logout:          'Logout',
    addItem:         'Add New Item',
    addOffer:        'Add Offer',
    addService:      'Add Service',
    edit:            'Edit',
    delete:          'Delete',
    actions:         'Actions',
    save:            'Save',
    cancel:          'Cancel',
    productName:     'Product Name (English)',
    productNameHi:   'Product Name (Hindi) — Optional',
    price:           'Price (₹)',
    stock:           'Stock Quantity',
    category:        'Category',
    description:     'Description (English)',
    descriptionHi:   'Description (Hindi) — Optional',
    uploadImage:     'Upload Product Image',
    offerTitle:      'Offer Title (English)',
    offerTitleHi:    'Offer Title (Hindi) — Optional',
    startDate:       'Start Date',
    endDate:         'End Date',
    bannerColor:     'Banner Color',
    serviceName:     'Service Name (English)',
    serviceNameHi:   'Service Name (Hindi) — Optional',
    serviceIcon:     'Icon (Emoji)',
    activeStatus:    'Active',
    totalItems:      'Total Items',
    activeOffers:    'Active Offers',
    totalServices:   'Total Services',
    quickActions:    'Quick Actions',
    confirmDelete:   'Are you sure you want to delete this?',
    yes:             'Yes, Delete',
    no:              'Cancel',
    loginTitle:      'Admin Login',
    username:        'Username',
    password:        'Password',
    login:           'Login',
    loginError:      'Invalid username or password',
    loading:         'Loading...',
    created:         'Created',
    updated:         'Updated',
    deleted:         'Deleted',
    error:           'Error',
    loadFailed:      'Failed to load data',
    deleteFailed:    'Delete failed',
    preview:         'Preview',
  },
  hi: {
    shopName:        'चौधरी कम्युनिकेशंस',
    welcome:         'चौधरी कम्युनिकेशंस में आपका स्वागत है!',
    welcomeSubtitle: 'मोबाइल, एक्सेसरीज और सेवाओं के लिए आपकी पसंदीदा दुकान',
    featuredItems:   'मुख्य उत्पाद',
    specialOffers:   'विशेष ऑफर',
    ourServices:     'हमारी सेवाएं',
    contactUs:       'संपर्क करें',
    whatsappUs:      'WhatsApp करें',
    callUs:          'कॉल करें',
    viewDetails:     'विवरण देखें',
    inStock:         'उपलब्ध है',
    outOfStock:      'उपलब्ध नहीं',
    noOffers:        'अभी कोई ऑफर नहीं है',
    adminPanel:      'एडमिन पैनल',
    dashboard:       'डैशबोर्ड',
    manageItems:     'उत्पाद प्रबंधन',
    manageOffers:    'ऑफर प्रबंधन',
    manageServices:  'सेवा प्रबंधन',
    logout:          'लॉगआउट',
    addItem:         'नया उत्पाद जोड़ें',
    addOffer:        'ऑफर जोड़ें',
    addService:      'सेवा जोड़ें',
    edit:            'संपादित करें',
    delete:          'हटाएं',
    actions:         'क्रियाएँ',
    save:            'सेव करें',
    cancel:          'रद्द करें',
    productName:     'उत्पाद का नाम (अंग्रेजी)',
    productNameHi:   'उत्पाद का नाम (हिंदी) — वैकल्पिक',
    price:           'मूल्य (₹)',
    stock:           'स्टॉक मात्रा',
    category:        'श्रेणी',
    description:     'विवरण (अंग्रेजी)',
    descriptionHi:   'विवरण (हिंदी) — वैकल्पिक',
    uploadImage:     'उत्पाद की छवि अपलोड करें',
    offerTitle:      'ऑफर का शीर्षक (अंग्रेजी)',
    offerTitleHi:    'ऑफर का शीर्षक (हिंदी) — वैकल्पिक',
    startDate:       'शुरू की तारीख',
    endDate:         'समाप्ति तारीख',
    bannerColor:     'बैनर रंग',
    serviceName:     'सेवा का नाम (अंग्रेजी)',
    serviceNameHi:   'सेवा का नाम (हिंदी) — वैकल्पिक',
    serviceIcon:     'आइकन (Emoji)',
    activeStatus:    'सक्रिय',
    totalItems:      'कुल उत्पाद',
    activeOffers:    'सक्रिय ऑफर',
    totalServices:   'कुल सेवाएं',
    quickActions:    'त्वरित कार्य',
    confirmDelete:   'क्या आप वाकई इसे हटाना चाहते हैं?',
    yes:             'हाँ, हटाएं',
    no:              'रद्द करें',
    loginTitle:      'एडमिन लॉगिन',
    username:        'यूजरनेम',
    password:        'पासवर्ड',
    login:           'लॉगिन करें',
    loginError:      'गलत यूजरनेम या पासवर्ड',
    loading:         'लोड हो रहा है...',
    created:         'बनाया गया',
    updated:         'अपडेट किया गया',
    deleted:         'हटा दिया गया',
    error:           'त्रुटि',
    loadFailed:      'डेटा लोड नहीं हो सका',
    deleteFailed:    'डिलीट नहीं हुआ',
    preview:         'पूर्वावलोकन',
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }){
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en')
  const toggleLang = () => { const next = lang === 'en' ? 'hi' : 'en'; setLang(next); localStorage.setItem('lang', next); }
  const t = (key) => translations[lang][key] || translations.en[key] || key
  return <LanguageContext.Provider value={{ lang, toggleLang, t }}>{children}</LanguageContext.Provider>
}

export const useLang = () => useContext(LanguageContext)
